name: CI Pipeline

on: [push]

jobs:
  build-linux:
    name: 'On Linux'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libeigen3-dev libglfw3-dev

    - name: Compile the shape_matching application
      run: |
        mkdir -p build
        cd build
        cmake .. || exit 1
        cmake --build . --target shape_matching_app || exit 1

    - name: List build directory
      run: ls -al build

    - name: Run the shape_matching application
      run: |
        ./cgogn/shape_matching_app || exit 1
