name: CI Pipeline

on: [push] 

jobs:
  build-linux:
    name: 'On Linux'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
    uses: actions/checkout@v2

    - name: Execute script 
    run: bash .\test.sh 




